server:
  port: 8080
spring:
  redis:
    port: 6379
    host: 192.168.198.135
    password: aaa759959801
    database: 0
    connect-timeout: 1800000
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        min-idle: 0
        max-idle: 5
  datasource:
    username: root
    password: aaa759959801
    url: jdbc:mysql://localhost:3306/seckill?rewriteBatchedStatements=true&serverTimezone=UTC&useSSL=true&userUnicode=true&characterEncoding=UTF-8&useInformationSchema=false
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.zhe.seckillsp.entity